machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  node:
    version: 7.10.0

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
  pre:
    - yarn global add now

test:
  override:
    - yarn test

deployment:
  production:
    branch: master
    commands: |
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        now --docker -t ${NOW_TOKEN} && now -t ${NOW_TOKEN} alias doug-march.com
      fi
